---
title: "Traumatic Brain Injury(TBI) statistics in the US"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
```


```{r loading libraries and files}
library(tidyverse)
library(lazyeval)
library(plotly)
tbi_age <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-24/tbi_age.csv')
tbi_year <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-24/tbi_year.csv')

#grouping by year and injury mechanism 
total_injuries <- tbi_year %>% filter(!is.na(number_est)) %>% group_by(year,injury_mechanism) %>% summarize(total=sum(number_est))
#grouping by year and death type
total_deaths <- tbi_year %>% filter(!is.na(number_est)) %>% filter(type=="Deaths") %>% group_by(year,type,injury_mechanism) %>% summarize(total=sum(number_est))


#spreading the dataframe to wide format 
total_injuries <- spread(total_injuries,injury_mechanism,total)
total_deaths <- spread(total_deaths,injury_mechanism,total)

#changing colnames 
colnames(total_injuries) <- c("year","Assault","Selfharm","MotorVehicle_Crashes","Nomechanism","Other_unintentionalinjury","Unintentional_falls","Unintentionallystruck")
total_injuries <- as.data.frame(total_injuries)

colnames(total_deaths) <- c("year","type","Assault","Selfharm","MotorVehicle_Crashes","Nomechanism", "Other_unintentionalinjury","Unintentional_falls","Unintentionallystruck")
total_deaths <- as.data.frame(total_deaths)

#function for adding a new column called frames for use in plotly 
#copied from the plotly tutorials
accumulate_by <- function(dat, var) {
  var <- f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  bind_rows(dats)
}

```

**March** is brain injury awareness month!
Lets taka a look at how common traumatic brain injuries are in the US.

[Data Source](https://www.cdc.gov/traumaticbraininjury/pdf/TBI-Surveillance-Report-FINAL_508.pdf)

```{r plot total injuries by year }

#adding frame column for plotting
total_injuries <- total_injuries %>% accumulate_by(~year)

#plotting total injuries 
injuries_plot <- plot_ly(total_injuries,x=~year,y=~Assault,frame=~frame,type="scatter",mode="plines",name="Assault") %>% add_trace(y=~Selfharm,type="scatter",mode="plines",name="Selfharm") %>% add_trace(y=~MotorVehicle_Crashes,type="scatter",mode="plines",name="Motor Vehicle Crashes") %>% add_trace(y=~Nomechanism,type="scatter",mode="plines",name="No mechanism") %>% add_trace(y=~Other_unintentionalinjury,type="scatter",mode="plines",name="Other unintentinal injury") %>% add_trace(y=~Unintentional_falls,type="scatter",mode="plines",name="Unintentional falls") %>% add_trace(y=~Unintentionallystruck,type="scatter",mode="plines",name="Unintentionally struck")

injuries_plot <- injuries_plot %>% animation_slider(currentvalue=list(prefix="Year "))

injuries_plot <- injuries_plot %>% layout(title="Total Brain Injuries by mechanism") %>% layout(yaxis=list(title=""))

injuries_plot
```


```{r plot total deaths by year}

#adding frame column for plotting 
total_deaths <- total_deaths %>% accumulate_by(~year)

#plotting total deaths 
deaths_plot <- plot_ly(total_deaths,x=~year,y=~Assault,frame=~frame,type="scatter",mode="plines",name="Assault") %>% add_trace(y=~Selfharm,type="scatter",mode="plines",name="Selfharm") %>% add_trace(y=~MotorVehicle_Crashes,type="scatter",model="plines",name="Motor Vehicle Crashes") %>% add_trace(y=~Nomechanism,type="scatter",model="plines",name="No mechanism") %>% add_trace(y=~Other_unintentionalinjury,type="scatter",model="plines",name="Other unintentinal injury") %>% add_trace(y=~Unintentional_falls,type="scatter",model="plines",name="Unintentional falls") %>% add_trace(y=~Unintentionallystruck,type="scatter",model="plines",name="Unintentionally struck")

deaths_plot <- deaths_plot %>% animation_slider(currentvalue=list(prefix="Year "))

deaths_plot <- deaths_plot %>% layout(title= "Total deaths from brain injuries by mechanism") %>% layout(yaxis=list(title=""))

deaths_plot
```

